### ISSUE TITLE
Need help: only html and plist generated.

### ISSUE THREAD

**Issue by magickaito** [gknops/adHocGenerate#1]
Hi, I tried the scripts but not sure which part I did wrongly.
When I created the script, the archive action in XCode only generated plist and html file.

More details of my situation is written here:
http://stackoverflow.com/questions/16994622/need-help-debugging-a-script-that-generates-ipa-and-plist-for-apple-enterprise-d

Anyone has any clues why is the ipa file not appearing?

**Comment by emresebat** [comment]
Hi,
This issue is closed without any comments, is there a solution for this?

**Comment by magickaito** [comment]
Hi,

Oh it was my mistake. There was a typo in one of the configurable path. There was a space in the folder name and when I copied the path of this folder from terminal, the space became " \" and the script failed to recognise the path. Removing the "\" works.

Regards,

Terrence Tee
